apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-yuanma-3d-object-detection
  namespace: inf-stud
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  storageClassName: retained  
